version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: expense_pg
    environment:
      POSTGRES_DB: expensetracker
      POSTGRES_USER: expensetracker
      POSTGRES_PASSWORD: 7303290820
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
